import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, Gift, Leaf, PackageCheck, ShieldCheck, Star, Truck } from "lucide-react";
import heroImage from "@/assets/asm-campaign-hero.jpg";
import categoryImage from "@/assets/asm-packaging-lineup.jpg";
import giftImage from "@/assets/asm-gift-box.jpg";
import { ProductCard } from "@/components/product-card";
import { StoreShell } from "@/components/store-shell";
import { Button } from "@/components/ui/button";
import { products } from "@/data/catalog";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "ASM Delights | Premium Dry Fruits, Nuts & Gift Boxes" },
    { name: "description", content: "Shop premium almonds, cashews, pistachios, dates, healthy mixes and elegant gift boxes from ASM Delights." },
    { property: "og:title", content: "ASM Delights | Premium Dry Fruits & Gifting" },
    { property: "og:description", content: "Freshly packed premium dry fruits and thoughtful gifts delivered across India." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }), component: HomePage,
});

const categories = [
  { name: "Almonds", slug: "nuts", pos: "object-[7%_50%]" }, { name: "Cashews", slug: "nuts", pos: "object-[25%_50%]" },
  { name: "Pistachios", slug: "nuts", pos: "object-[43%_50%]" }, { name: "Dates", slug: "dry-fruits", pos: "object-[61%_50%]" },
  { name: "Walnuts", slug: "nuts", pos: "object-[79%_50%]" }, { name: "Healthy Mixes", slug: "berries-seeds", pos: "object-[96%_50%]" },
];

function HomePage() {
  return <StoreShell>
    <section className="relative min-h-[430px] overflow-hidden sm:min-h-[500px] lg:min-h-[570px]"><img src={heroImage} alt="ASM Delights premium dry fruits in maroon and gold packaging" width={1920} height={840} className="absolute inset-0 h-full w-full object-cover object-[72%_center] sm:object-[66%_center]"/><div className="absolute inset-0 bg-secondary/80 sm:bg-hero-overlay"/><div className="relative mx-auto flex min-h-[430px] max-w-[1440px] items-center px-5 py-14 sm:min-h-[500px] lg:min-h-[570px] lg:px-10"><div className="max-w-xl"><p className="text-xs font-extrabold uppercase text-accent-foreground">A premium everyday ritual</p><h1 className="mt-3 font-display text-4xl font-bold leading-tight text-primary sm:text-5xl lg:text-6xl">Goodness you can see. Quality you can taste.</h1><p className="mt-5 max-w-lg text-sm leading-7 text-foreground sm:text-base">Handpicked dry fruits, nuts and nourishing mixes—freshly packed and made for better snacking.</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/shop">Shop now <ArrowRight/></Link></Button><Button asChild variant="outline" size="lg"><Link to="/gifting">Explore gifting</Link></Button></div></div></div></section>
    <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-[1440px] grid-cols-2 gap-px bg-border lg:grid-cols-4">{[[ShieldCheck,"Purity checked","Carefully selected"],[PackageCheck,"Freshly packed","Small, careful batches"],[Truck,"Pan-India delivery","Free above ₹999"],[BadgeCheck,"Premium quality","Satisfaction assured"]].map(([Icon,title,copy]) => { const TrustIcon = Icon as typeof ShieldCheck; return <div key={title as string} className="flex items-center gap-3 bg-card px-4 py-5 sm:justify-center"><TrustIcon size={22} className="shrink-0 text-accent"/><div><p className="text-xs font-extrabold text-foreground sm:text-sm">{title as string}</p><p className="text-[10px] text-muted-foreground sm:text-xs">{copy as string}</p></div></div>; })}</div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-12 lg:px-10 lg:py-16"><div className="mb-7 flex items-end justify-between"><div><p className="text-xs font-extrabold uppercase text-accent-foreground">Shop your favourites</p><h2 className="mt-2 font-display text-3xl font-bold text-primary">Shop by category</h2></div><Link to="/shop" className="hidden items-center gap-1 text-sm font-bold text-primary sm:flex">View all <ArrowRight size={16}/></Link></div><div className="hide-scrollbar flex gap-4 overflow-x-auto pb-2">{categories.map((category) => <Link key={category.name} to="/collections/$category" params={{ category: category.slug }} className="group min-w-[125px] text-center sm:min-w-[165px]"><div className="aspect-square overflow-hidden rounded-full border border-border bg-secondary"><img src={categoryImage} alt={category.name} loading="lazy" width={1800} height={1200} className={`h-full w-full scale-[3.5] object-cover ${category.pos} transition-transform duration-500 group-hover:scale-[3.65]`}/></div><p className="mt-3 text-sm font-bold text-foreground">{category.name}</p></Link>)}</div></section>
    <section className="bg-muted py-12 lg:py-16"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="mb-8 text-center"><p className="text-xs font-extrabold uppercase text-accent-foreground">Customers keep coming back</p><h2 className="mt-2 font-display text-3xl font-bold text-primary">Our bestsellers</h2></div><div className="grid grid-cols-2 gap-x-3 gap-y-8 md:grid-cols-3 lg:grid-cols-4 lg:gap-5">{products.slice(0,8).map((product) => <ProductCard key={product.slug} product={product}/>)}</div><div className="mt-10 text-center"><Button asChild variant="outline" size="lg"><Link to="/shop">View all products <ArrowRight/></Link></Button></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-12 lg:px-10 lg:py-16"><div className="grid overflow-hidden rounded-md bg-secondary lg:grid-cols-2"><div className="min-h-[320px]"><img src={giftImage} alt="ASM Delights premium dry fruit gift box" loading="lazy" width={1600} height={1000} className="h-full w-full object-cover"/></div><div className="flex flex-col justify-center p-8 sm:p-12 lg:p-16"><p className="text-xs font-extrabold uppercase text-accent-foreground">Celebrate with good taste</p><h2 className="mt-3 font-display text-3xl font-bold leading-tight text-primary sm:text-4xl">Gifts that feel as special as the occasion.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-muted-foreground">Premium assortments in elegant maroon and gold boxes for festivals, weddings, teams and thoughtful everyday moments.</p><ul className="mt-5 grid gap-2 text-sm font-semibold text-foreground sm:grid-cols-2"><li className="flex gap-2"><Gift size={17} className="text-accent"/>Custom gift notes</li><li className="flex gap-2"><Gift size={17} className="text-accent"/>Corporate orders</li></ul><Button asChild className="mt-7 w-fit" size="lg"><Link to="/gifting">Explore gift boxes <ArrowRight/></Link></Button></div></div></section>
    <section className="border-y border-border bg-primary py-14 text-primary-foreground"><div className="mx-auto max-w-5xl px-5 text-center"><Leaf className="mx-auto text-accent"/><h2 className="mt-4 font-display text-3xl font-bold">Better snacking begins with better ingredients.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-primary-foreground/75">We select for taste, texture and purity, then pack in small batches so every pouch reaches you at its best.</p><Button asChild variant="secondary" className="mt-7"><Link to="/about">Our story <ArrowRight/></Link></Button></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-12 lg:px-10 lg:py-16"><div className="mb-8 text-center"><p className="text-xs font-extrabold uppercase text-accent-foreground">Real moments of delight</p><h2 className="mt-2 font-display text-3xl font-bold text-primary">Loved across India</h2></div><div className="grid gap-4 md:grid-cols-3">{[["The almonds are crisp and genuinely fresh. The resealable pack is perfect for our breakfast shelf.","Aarav M.","Mumbai"],["Sent the Royal Gift Box to family for Diwali. It looked elegant and arrived beautifully packed.","Neha R.","Bengaluru"],["My evening snack is sorted. The trail mix feels balanced, not overly sweet.","Ritika S.","Delhi"]].map(([quote,name,city]) => <figure key={name} className="rounded-md border border-border bg-card p-6"><div className="flex gap-1 text-rating">{[1,2,3,4,5].map(i=><Star key={i} size={15} fill="currentColor"/>)}</div><blockquote className="mt-4 text-sm leading-7 text-foreground">“{quote}”</blockquote><figcaption className="mt-5 text-xs font-bold text-primary">{name} <span className="font-medium text-muted-foreground">• {city}</span></figcaption></figure>)}</div></section>
    <section className="border-t border-border bg-secondary py-12"><div className="mx-auto max-w-2xl px-5 text-center"><h2 className="font-display text-3xl font-bold text-primary">A little delight in your inbox</h2><p className="mt-2 text-sm text-muted-foreground">Fresh launches, festive collections and members-only offers.</p><form onSubmit={(event) => event.preventDefault()} className="mx-auto mt-6 flex max-w-lg gap-2"><input required type="email" aria-label="Email address" placeholder="Enter your email address" className="h-11 min-w-0 flex-1 rounded-md border border-input bg-card px-4 text-sm outline-none focus:ring-1 focus:ring-ring"/><Button type="submit" className="h-11">Subscribe</Button></form></div></section>
  </StoreShell>;
}