import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ProductCard } from "@/components/product-card";
import { StoreShell } from "@/components/store-shell";
import { Button } from "@/components/ui/button";
import { products } from "@/data/catalog";

export const Route = createFileRoute("/shop")({ head: () => ({ meta: [{ title: "Shop All Dry Fruits & Nuts | ASM Delights" }, { name: "description", content: "Browse premium dry fruits, nuts, healthy mixes and gift boxes from ASM Delights." }, { property: "og:title", content: "Shop ASM Delights" }, { property: "og:description", content: "Fresh premium dry fruits, nuts and gifts for every occasion." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ShopPage });

function ShopPage() {
  const [category, setCategory] = useState("all"); const [sort, setSort] = useState("featured");
  const shown = useMemo(() => { const list = category === "all" ? [...products] : products.filter(p => p.category === category); if (sort === "low") list.sort((a,b)=>a.price-b.price); if (sort === "high") list.sort((a,b)=>b.price-a.price); return list; }, [category, sort]);
  return <StoreShell><section className="border-b border-border bg-secondary"><div className="mx-auto max-w-[1440px] px-5 py-12 text-center lg:px-10"><p className="text-xs font-extrabold uppercase text-accent-foreground">The pantry edit</p><h1 className="mt-2 font-display text-4xl font-bold text-primary">Shop all delights</h1><p className="mx-auto mt-3 max-w-xl text-sm text-muted-foreground">Premium everyday staples, nourishing snacks and celebration-ready gifts.</p></div></section><section className="mx-auto max-w-[1440px] px-5 py-10 lg:px-10"><div className="mb-8 flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-center sm:justify-between"><div className="hide-scrollbar flex gap-2 overflow-x-auto">{[["all","All"],["nuts","Nuts"],["dry-fruits","Dry fruits"],["berries-seeds","Mixes & seeds"],["gifting","Gifting"]].map(([value,label])=><Button key={value ?? label} variant={category===value?"default":"outline"} size="sm" onClick={()=>value&&setCategory(value)}>{label}</Button>)}</div><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)} className="h-10 rounded-md border border-input bg-card px-3 text-sm"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><p className="mb-6 text-xs text-muted-foreground">{shown.length} products</p><div className="grid grid-cols-2 gap-x-3 gap-y-9 md:grid-cols-3 lg:grid-cols-4 lg:gap-5">{shown.map(product=><ProductCard key={product.slug} product={product}/>)}</div></section></StoreShell>;
}