/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPanelRouteImport } from './routes/admin._panel'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminPanelCustomersRouteImport } from './routes/admin._panel.customers'
import { Route as AdminPanelDashboardRouteImport } from './routes/admin._panel.dashboard'
import { Route as AdminPanelProfileRouteImport } from './routes/admin._panel.profile'
import { Route as AdminPanelReportsRouteImport } from './routes/admin._panel.reports'
import { Route as AdminPanelTransactionsRouteImport } from './routes/admin._panel.transactions'
import { Route as AdminPanelOrdersIndexRouteImport } from './routes/admin._panel.orders.index'
import { Route as AdminPanelOrdersIdRouteImport } from './routes/admin._panel.orders.$id'
import { Route as AdminPanelProductsIndexRouteImport } from './routes/admin._panel.products.index'
import { Route as AdminPanelProductsNewRouteImport } from './routes/admin._panel.products.new'
import { Route as AdminPanelProductsSlugEditRouteImport } from './routes/admin._panel.products.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelCustomersRoute = AdminPanelCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDashboardRoute = AdminPanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProfileRoute = AdminPanelProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelReportsRoute = AdminPanelReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelTransactionsRoute = AdminPanelTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelOrdersIndexRoute = AdminPanelOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelOrdersIdRoute = AdminPanelOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProductsIndexRoute = AdminPanelProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProductsNewRoute = AdminPanelProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProductsSlugEditRoute =
  AdminPanelProductsSlugEditRouteImport.update({
    id: '/products/$slug/edit',
    path: '/products/$slug/edit',
    getParentRoute: () => AdminPanelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gifting': typeof GiftingRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers': typeof AdminPanelCustomersRoute
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/profile': typeof AdminPanelProfileRoute
  '/admin/reports': typeof AdminPanelReportsRoute
  '/admin/transactions': typeof AdminPanelTransactionsRoute
  '/admin/orders/$id': typeof AdminPanelOrdersIdRoute
  '/admin/products/new': typeof AdminPanelProductsNewRoute
  '/admin/orders/': typeof AdminPanelOrdersIndexRoute
  '/admin/products/': typeof AdminPanelProductsIndexRoute
  '/admin/products/$slug/edit': typeof AdminPanelProductsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gifting': typeof GiftingRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/customers': typeof AdminPanelCustomersRoute
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/profile': typeof AdminPanelProfileRoute
  '/admin/reports': typeof AdminPanelReportsRoute
  '/admin/transactions': typeof AdminPanelTransactionsRoute
  '/admin/orders/$id': typeof AdminPanelOrdersIdRoute
  '/admin/products/new': typeof AdminPanelProductsNewRoute
  '/admin/orders': typeof AdminPanelOrdersIndexRoute
  '/admin/products': typeof AdminPanelProductsIndexRoute
  '/admin/products/$slug/edit': typeof AdminPanelProductsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gifting': typeof GiftingRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/_panel': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_panel/customers': typeof AdminPanelCustomersRoute
  '/admin/_panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin/_panel/profile': typeof AdminPanelProfileRoute
  '/admin/_panel/reports': typeof AdminPanelReportsRoute
  '/admin/_panel/transactions': typeof AdminPanelTransactionsRoute
  '/admin/_panel/orders/$id': typeof AdminPanelOrdersIdRoute
  '/admin/_panel/products/new': typeof AdminPanelProductsNewRoute
  '/admin/_panel/orders/': typeof AdminPanelOrdersIndexRoute
  '/admin/_panel/products/': typeof AdminPanelProductsIndexRoute
  '/admin/_panel/products/$slug/edit': typeof AdminPanelProductsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gifting'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/admin/login'
    | '/api/chat'
    | '/collections/$category'
    | '/products/$slug'
    | '/admin/'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/transactions'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/products/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assistant'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gifting'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/admin'
    | '/admin/login'
    | '/api/chat'
    | '/collections/$category'
    | '/products/$slug'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/transactions'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/products/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gifting'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/track-order'
    | '/admin/_panel'
    | '/admin/login'
    | '/api/chat'
    | '/collections/$category'
    | '/products/$slug'
    | '/admin/'
    | '/admin/_panel/customers'
    | '/admin/_panel/dashboard'
    | '/admin/_panel/profile'
    | '/admin/_panel/reports'
    | '/admin/_panel/transactions'
    | '/admin/_panel/orders/$id'
    | '/admin/_panel/products/new'
    | '/admin/_panel/orders/'
    | '/admin/_panel/products/'
    | '/admin/_panel/products/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GiftingRoute: typeof GiftingRoute
  PrivacyRoute: typeof PrivacyRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ApiChatRoute: typeof ApiChatRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_panel': {
      id: '/admin/_panel'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel/customers': {
      id: '/admin/_panel/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminPanelCustomersRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/dashboard': {
      id: '/admin/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminPanelDashboardRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/profile': {
      id: '/admin/_panel/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminPanelProfileRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/reports': {
      id: '/admin/_panel/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminPanelReportsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/transactions': {
      id: '/admin/_panel/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminPanelTransactionsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/orders/': {
      id: '/admin/_panel/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminPanelOrdersIndexRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/orders/$id': {
      id: '/admin/_panel/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminPanelOrdersIdRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/products/': {
      id: '/admin/_panel/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminPanelProductsIndexRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/products/new': {
      id: '/admin/_panel/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminPanelProductsNewRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/products/$slug/edit': {
      id: '/admin/_panel/products/$slug/edit'
      path: '/products/$slug/edit'
      fullPath: '/admin/products/$slug/edit'
      preLoaderRoute: typeof AdminPanelProductsSlugEditRouteImport
      parentRoute: typeof AdminPanelRoute
    }
  }
}

interface AdminPanelRouteChildren {
  AdminPanelCustomersRoute: typeof AdminPanelCustomersRoute
  AdminPanelDashboardRoute: typeof AdminPanelDashboardRoute
  AdminPanelProfileRoute: typeof AdminPanelProfileRoute
  AdminPanelReportsRoute: typeof AdminPanelReportsRoute
  AdminPanelTransactionsRoute: typeof AdminPanelTransactionsRoute
  AdminPanelOrdersIdRoute: typeof AdminPanelOrdersIdRoute
  AdminPanelProductsNewRoute: typeof AdminPanelProductsNewRoute
  AdminPanelOrdersIndexRoute: typeof AdminPanelOrdersIndexRoute
  AdminPanelProductsIndexRoute: typeof AdminPanelProductsIndexRoute
  AdminPanelProductsSlugEditRoute: typeof AdminPanelProductsSlugEditRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelCustomersRoute: AdminPanelCustomersRoute,
  AdminPanelDashboardRoute: AdminPanelDashboardRoute,
  AdminPanelProfileRoute: AdminPanelProfileRoute,
  AdminPanelReportsRoute: AdminPanelReportsRoute,
  AdminPanelTransactionsRoute: AdminPanelTransactionsRoute,
  AdminPanelOrdersIdRoute: AdminPanelOrdersIdRoute,
  AdminPanelProductsNewRoute: AdminPanelProductsNewRoute,
  AdminPanelOrdersIndexRoute: AdminPanelOrdersIndexRoute,
  AdminPanelProductsIndexRoute: AdminPanelProductsIndexRoute,
  AdminPanelProductsSlugEditRoute: AdminPanelProductsSlugEditRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

interface AdminRouteChildren {
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GiftingRoute: GiftingRoute,
  PrivacyRoute: PrivacyRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  ApiChatRoute: ApiChatRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
